[package]
name = "suffix-array"
version = "0.1.0"
edition = "2021"

[dependencies]
rand = { version = "0.9.0-beta.1", features = [] }
plotters = "0.3.7"
serde_json = "1.0.140"
serde = { version = "1.0.218", features = ["derive"] }

[features]
verbose = []
